### ISSUE TITLE
Nice plugin

### ISSUE THREAD

**Issue by pierreyves-lebrun** [alDuncanson/react-hooks-snippets#1]
At first thanks for this convenient plugin for react hooks, I find it really nice!

Let me please just highlight the fact it is relying on automatic semicolon insertion, which is controversial within the EcmaScript community.

For example, the `ush` shortcut is missing a colon at the end of the following statement:
`const [, set] = useState()` <- Missing colon

**Comment by alDuncanson** [comment]
Hi @pierreyves-lebrun , I'm glad you like the extension! I was unsure how to approach this, as I do not use semicolons where they are not needed. Is it safe to say that the majority of people would prefer if I added semicolons? Or would you prefer I add functionality such as adding `wos` or `ws` at the end of the hook abbreviation to indicate `with semicolons` or `without semicolons`?

**Comment by pierreyves-lebrun** [comment]
Thanks for your reply, I have to say I am not sure whether a majority of ES devs do prefer writing code with semicolons. People tend to be very opinionated and even passionate about this particular matter.

Personally I would love not using semicolons, but after making a lot of research I concluded that it probably is better to use them for the sake of consistency.

There are plenty of articles about it on the internet, but omitting semicolons can lead to bugs in certain cases:
https://medium.freecodecamp.org/codebyte-why-are-explicit-semicolons-important-in-javascript-49550bea0b82

Some people will argue that such problems can be avoided by writing code differently, however, having to do that sounds awfully wrong to me.

In any case, that is only my personal view so I guess people should have the choice to use or omit them.

I was wondering if it could simply be an option to turn on/off in VSCode settings panel. Do you think it would be possible?

**Comment by alDuncanson** [comment]
@pierreyves-lebrun I agree, I can look into that!

If I can't figure out how to make a toggle on/off option, I can edit the snippets to include the semicolons by default, since that seems to please the majority. I'll put some thought into options

**Comment by alDuncanson** [comment]
added semicolons, closing now

**Comment by pierreyves-lebrun** [comment]
Thanks a lot, much appreciated!

**Comment by alDuncanson** [comment]
> Thanks a lot, much appreciated!

No problem @pierreyves-lebrun , there seems to be an issue with Microsoft's vsce tool so once that is figured out the extension will be updated on the marketplace. Then I'll re-close the issue :+1:

**Comment by alDuncanson** [comment]
Everything seems to have updated finally! Thanks for sticking around :)
