### ISSUE TITLE
not working in tsx

### ISSUE THREAD

**Issue by lokewei** [alDuncanson/react-hooks-snippets#10]
![problem](https://user-images.githubusercontent.com/1223119/60170553-3a4b0c00-983b-11e9-869a-941c127fe468.gif)

**Comment by alDuncanson** [comment]
Hi @lokewei I'll look into it right now!

**Comment by alDuncanson** [comment]
Alrighty, I just re-deployed the extension, version 1.1.5 now supports typescript!
