### ISSUE TITLE
useEffect snippet with misleading comment

### ISSUE THREAD

**Issue by andremiguelaa** [alDuncanson/react-hooks-snippets#11]
In `useEffect` snippet you have a comment saying that cleanup will run when the component will unmount but that's not the only moment cleanup runs.
In fact, `cleanup` is invoked whenever the component is being re-rendered (including unmount)

**Comment by alDuncanson** [comment]
Ah, you are right @andremiguelaa . I can actually remove the comments entirely if you think they are misleading. I initially was using them because when people first started to adopt hooks, the useEffect hook was confusing to most.

**Comment by andremiguelaa** [comment]
You can leave them with a better description or get rid of them.
If you ask my opinion, I rather get rid of them. The main advantage of using snippets is to write less code but, with comments, I have to remove them and that way I will loose some time I just saved using the snippet.

**Comment by alDuncanson** [comment]
@andremiguelaa removed the comments in version 1.1.6 :ok_hand:

**Comment by andremiguelaa** [comment]
Thanks, @alDuncanson !
