### ISSUE TITLE
Incompatibility with VSCode version 1.36.1

### ISSUE THREAD

**Issue by wfcastaneda** [alDuncanson/react-hooks-snippets#14]
Hi,

First of all, this plugin looks great!

I tried installing through it through the VSCode plugin interface, manually using the `.vsix` file, and thorugh the VSCode Command Palette. The first two methods failed, but didn't indicate the issue through in the generic error that was presented. The Command Palette did indicate the issue -- This is the error I was presented with: `'alduncanson.react-hooks-snippets' compatible with current version '1.26.1' of VS Code is not found.`.

I will fork this and see if I can resolve the issue, but I wanted to make all aware of the issue with the current version `1.26.1` of Code.

Thanks!

Will

**Comment by alDuncanson** [comment]
Sorry I'm just now getting around to this; Thanks @wfcastaneda !

So you were able to resolve the issue then?
