### ISSUE TITLE
Custom settings for snippets

### ISSUE THREAD

**Issue by dannyxnda** [alDuncanson/react-hooks-snippets#15]
Hi,
I want to use the snippets with my custom settings.
For example, if I type `ueh`, it will automatically create `return cleanUp = () => {}` although I don't want it.
You know, we hardly have a cleanup callback except for some special cases such as `setTimeout, setInterval, ...`.
Please tell me if you can somehow improve this situation.
I do appreciate this extension.
Thanks!

**Comment by alDuncanson** [comment]
Hey @and0705 thanks for the suggestion. In order to add extension controls with json settings I'll have to rebuild the extension in Typescript to allow for json setting contributions. 

I have been planning to do so but can't give you a definitive timeline since this'll be new territory for me. I'll keep this issue open so I can let you know when I get around to it!

**Comment by dan0705** [comment]
> Hey @dan0705 thanks for the suggestion. In order to add extension controls with json settings I'll have to rebuild the extension in Typescript to allow for json setting contributions.
> 
> I have been planning to do so but can't give you a definitive timeline since this'll be new territory for me. I'll keep this issue open so I can let you know when I get around to it!

I'm looking forward to using it. Thank you!

**Comment by rsxdalv** [comment]
Maybe just a setting to disable the cleanUp = () syntax? I'm pretty sure that syntax will generate errors with most linters not just TypeScript.

**Comment by alDuncanson** [comment]
Hey thanks for the reminder @rsxdalv , I still plan on tackling this.

The project got away from me for a little while but I don't see why re-writing it in Typescript would be an issue. Once that's done, we'll have the ability to add options for different variations of hooks, semi/no-semi, etc 👍🏻

**Comment by alDuncanson** [comment]
I no longer have the time to add new features to this extension, feel free to open a pr if you have the time!

**Comment by rsxdalv** [comment]
I understand and I'm in the same boat. I think if someone really needs
this, they could make another "ueh2" snippet without the cleanup.
Personally I think with AI code completion I barely need snippets anymore.
