### ISSUE TITLE
Move from snippet extension into something more

### ISSUE THREAD

**Issue by zardoy** [alDuncanson/react-hooks-snippets#19]
I think this extension has a great future! https://github.com/alDuncanson/react-hooks-snippets/issues/15#issuecomment-718782937 Of course with preserving web support!
I've been trying to build a similar extension: https://github.com/zardoy/vscode-better-snippets (it was primarily created for React). I still need to tidy up the code and implement tests, but I want to share my experience with you!

## Configuration

- override name of snippets and disable with `false`. From there we can also add more snippets (since user can rename them) like `useEffect` without cleanup
- snippet-specific options
  - enable/disable tabstops in deps (`useCallback` ...)

## Where to Show

Most of the snippets would make sense to show only in one place: body of top-level function.
Since we have now more control in completion provider, we can exclude annoying snippet suggestions in other places (such as in props of components).
The first solution I used was to show snippets only [in start of line](https://github.com/zardoy/vscode-better-snippets/blob/ec1c572c67d213121cdb00571c3a90e39bb851e3/test/snippets.jsonc#L13).
However it was still annoying to see them in JSX:
```tsx
const Component = () => {
    // this place is great
    return <div>
        {/* this place is bad */}
    </div>
}
```
So I added additional check to ensure that line on one level above [is function](https://github.com/zardoy/vscode-better-snippets/blob/ec1c572c67d213121cdb00571c3a90e39bb851e3/test/snippets.jsonc#L23).
However regexs are obviously bad for code parsing, as it would work only if whole function declaration on the same line.
The check can (and should) be rewritten using TS language service, this is only matter of performance.

## Auto Reformat

There shouldn't be an options like `semi`, because user can use it in different existing projects (legacy/new). Configuring it locally would be annoying, instead it should infer the codestyle from it. I'm still thinking of the best solution, but I think the easiest way is ask TypeScript language service.

## Auto imports :fire:

It would be hardcoded.

This is what I love most. I see you have snippet for hooks import, but it is not ideal for existing projects and leaving all unused imports is a known bad practice.

This works by just querying diagnostics to see wether we have missing identifiers and then code actions to add import them if needed. It happens with specific delay of course, since TypeScript is extremely slow.
In theory we can also use language service here instead.

[example config](https://github.com/zardoy/vscode-better-snippets/blob/ec1c572c67d213121cdb00571c3a90e39bb851e3/test/snippets.jsonc#L30)
It seeks for import suggestions from `react` package. In case of custom redux dispatcher we can omit `package` field:
```jsonc
"resolveImports": {
    "useAppDispatch": {}
},
```
It means we can also implement support for imports with dynamic paths.

[GIF Demo](https://twitter.com/zardo96/status/1483052969222602755)

## Special Snippets

We can also provide even more useful snippets. For example I created 

For example I have special snippet for users of `react-router`: [`useParam`](https://github.com/zardoy/vscode-better-snippets/blob/main/src/specialCommand.ts#L11).

[GIF Demo](https://twitter.com/zardo96/status/1482817282145492993)

It is kinda hardcoded, :
1. Find exported symbol (component) with the same name as file (currently doesn't work with default exports)
2. Find second reference for it (first one is import)
3. Extract params by using regex (again, we should use AST parsing instead)

Also we should support folks using `remix`. It would be easy since we only need to parse path to file.

Of course I want to remove it from my ext (move to yours).

## Nice React Icon

<img src="https://user-images.githubusercontent.com/46503702/174414480-70f6235a-5d0d-4c58-bd1b-8e97533bb085.png" width="500" alt="react vscode snippet icon" />

It works only with [vscode-icons](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons). So we should enable it only if this extension is installed

## What's next?

- LSP. Unique platform.

## What we shouldn't aim

Refactors! For example sometimes it's much easier to extract existing code to `useCallback` without using snippets, but code actions. [Abracadabra](https://github.com/nicoespeon/abracadabra) already [can handle it](https://github.com/nicoespeon/abracadabra/blob/main/REFACTORINGS.md#extract-usecallback)

Feel free to test everything yourself if you want. Everything above shouldn't be hard to implement. Hope I gave you some inspiration.

**Comment by alDuncanson** [comment]
Wow thanks for the write up!

I like the auto imports a lot 👍🏻 Nice work
