### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [alDuncanson/react-hooks-snippets#2]
I installed your extension, opened a random jsx file, typed in what you said. Nothing appears.

**Comment by alDuncanson** [comment]
Hi @hp8wvvvgnj6asjm7 , which snippet were you trying to use? Did you save the `.jsx` file before you started typing in it? Have you tried restarting VS Code?

**Comment by hp8wvvvgnj6asjm7** [comment]
Yes and yes, but it seems that v1.3.3 has some problems with intellisense being slow. This could be an issue with VSCode right now. Thank you

**Comment by alDuncanson** [comment]
No problem @hp8wvvvgnj6asjm7 , closing as this is related to VSCode
