### ISSUE TITLE
useState uppercase/lowercase feature request

### ISSUE THREAD

**Issue by andreifilip123** [alDuncanson/react-hooks-snippets#9]
Hey there!

Really love your extension. I'm having a small problem with it though.
When I'm creating a useState hook I expect it to look like this:
`const [fooBar, setFooBar] = useState(0);`
Right now, it looks like this:
`const [fooBar, setfooBar] = useState(0);`
Any chance you could make the first letter after set uppercase ?

Thanks a lot :)

**Comment by iamandiradu** [comment]
Yup, that uppercase would be nice.

**Comment by alDuncanson** [comment]
Hey @andreifilip123 , are you hitting tab after typing `fooBar`? Currently the snippet should be capitalizing for you like this: 
![ush](https://user-images.githubusercontent.com/25286675/59858337-cbf0e000-9348-11e9-9fbf-99932ef65399.gif)

**Comment by iamandiradu** [comment]
I'm pressing 'Enter' actually. Will try the 'Tab' tomorrow. Thanks, @alDuncanson !

**Comment by alDuncanson** [comment]
No problem @iamandiradu :+1:

**Comment by andreifilip123** [comment]
I actually tried it right now and it doesn't seem to work.

![fooBar](https://user-images.githubusercontent.com/8095119/59866623-b0abc200-9394-11e9-9bc1-81ca851c354b.gif)

**Comment by alDuncanson** [comment]
> I actually tried it right now and it doesn't seem to work.
> 
> ![fooBar](https://user-images.githubusercontent.com/8095119/59866623-b0abc200-9394-11e9-9bc1-81ca851c354b.gif)

Interesting :thinking: .. I'm not exactly sure what could cause the difference for yours vs mine. Mind sharing your settings?

**Comment by andreifilip123** [comment]
I realized that it's because of my vim plugin. When I turn it off, it works as expected. Any idea why that might happen? 🤔

**Comment by alDuncanson** [comment]
Interesting, you mean you are emulating Vim in VS Code?

**Comment by andreifilip123** [comment]
Yes. Using this:
https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

**Comment by frederickfogerty** [comment]
Hey @andreifilip123 did you ever get this working with the vim plugin enabled? I can't seem to get it working either :/

**Comment by andreifilip123** [comment]
No, I don't really use the extension that much anymore. Sorry.

**Comment by frederickfogerty** [comment]
All good, thanks for the reply @andreifilip123 🙌
